## Numpy

Импортировать NumPy под именем np

In [2]:
import numpy as np

Создать вектор (одномерный массив) размера 10, заполненный нулями

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Создать вектор размера 10, заполненный единицами

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Создать вектор размера 10, заполненный числом 2.5

In [5]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [7]:
v = np.zeros(10)
v[4] = 1
v

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

Развернуть вектор (первый становится последним)

In [10]:
v = np.arange(10)
v = v[::-1]
v

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [11]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [12]:
np.nonzero([1, 2, 0, 0, 4, 0])

(array([0, 1, 4], dtype=int64),)

Создать 3x3 единичную матрицу

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Создать массив 3x3x3 со случайными значениями

In [14]:
np.random.random((3,3,3))

array([[[9.63436769e-01, 2.82948128e-01, 2.23094562e-01],
        [4.06573887e-01, 5.42049620e-01, 9.19275962e-01],
        [5.86969447e-01, 1.09130218e-01, 2.85576092e-01]],

       [[1.24181232e-01, 8.88627231e-04, 8.72871222e-01],
        [5.56603466e-01, 1.29540053e-02, 4.01737734e-01],
        [8.47353459e-01, 4.87777040e-01, 5.52855555e-02]],

       [[5.47222353e-01, 8.74684692e-01, 8.21608619e-01],
        [8.93152559e-01, 8.02623267e-01, 1.08615377e-01],
        [6.56879759e-01, 2.29474082e-01, 6.45897782e-01]]])

Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [18]:
np.random.random(30).mean()

0.5576595327168101

Перемножить матрицы 5x3 и 3x2

In [25]:
a = np.arange(15).reshape(5, 3)
b = np.arange(-6, 0).reshape(3, 2)
np.dot(a, b)

array([[  -8,   -5],
       [ -44,  -32],
       [ -80,  -59],
       [-116,  -86],
       [-152, -113]])

Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [35]:
np.linspace(0,1,11,False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

Заменить максимальный элемент на ноль

In [38]:
a = np.arange(15)
indx = a.argmax()
a[indx] = 0
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13,  0])

Преобразовать массив из float в int

In [45]:
v = np.random.random(10) * 10
print(v)
print(v.astype(np.int32))

[5.57656896 1.55934622 3.34882914 7.82178697 1.73677985 5.6410081
 6.61171717 2.83197307 9.52682295 7.53662585]
[5 1 3 7 1 5 6 2 9 7]


Дан массив (10,2) координат, найти расстояние от каждой точки до каждой

In [54]:
import scipy.spatial as spatial

a = np.random.random((10,2))
spatial.distance.cdist(a, a)

array([[0.        , 0.21856291, 0.77262347, 0.54011922, 0.44421591,
        0.40674275, 0.29210629, 0.47662619, 0.37893498, 0.29295099],
       [0.21856291, 0.        , 0.80785575, 0.75036297, 0.58817243,
        0.52103631, 0.4758119 , 0.67843541, 0.5487672 , 0.37796357],
       [0.77262347, 0.80785575, 0.        , 0.77569394, 0.44665083,
        0.40486641, 0.60537205, 0.68730332, 0.5413844 , 1.06459881],
       [0.54011922, 0.75036297, 0.77569394, 0.        , 0.34806856,
        0.4327459 , 0.29905887, 0.09785511, 0.2825323 , 0.67632643],
       [0.44421591, 0.58817243, 0.44665083, 0.34806856, 0.        ,
        0.09752073, 0.18101111, 0.25209357, 0.09800829, 0.70370124],
       [0.40674275, 0.52103631, 0.40486641, 0.4327459 , 0.09752073,
        0.        , 0.20148284, 0.3350022 , 0.15489928, 0.68568797],
       [0.29210629, 0.4758119 , 0.60537205, 0.29905887, 0.18101111,
        0.20148284, 0.        , 0.21133327, 0.09237849, 0.52785558],
       [0.47662619, 0.67843541, 0.6873033

Случайно расположить p элементов в 2D массив

In [67]:
n = 5
p = 11
a = np.zeros((n,n))
np.put(a, np.random.choice(range(n*n), p, replace=True), 1)
a

array([[0., 0., 1., 0., 0.],
       [1., 1., 0., 1., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 1., 1.]])

Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [75]:
a = np.zeros(17)
a[::4] = np.array([1,2,3,4,5])
a

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

Найти наиболее частое значение в массиве

In [95]:
a = np.random.randint(0,5,10)
print(a)
np.bincount(a).argmax()

[0 2 3 1 2 3 4 3 1 3]


3

Найти n наибольших значений в массиве

In [93]:
n = 3
a = np.arange(10)
np.random.shuffle(a)
np.sort(a)[-n:]

array([7, 8, 9])

## Pandas - изучение данных

Перейти по ссылке [Kaggle]( https://www.kaggle.com/openfoodfacts/world-food-facts)

Скачать датасет на свой компьютер и распаковать

Считать csv файл в датафрейм food

In [135]:
import pandas as pd
food = pd.read_csv('en.openfoodfacts.org.products.tsv', sep='\t', low_memory=False)
print(food.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 356027 entries, 0 to 356026
Columns: 163 entries, code to water-hardness_100g
dtypes: float64(107), object(56)
memory usage: 442.8+ MB
None


Посмотреть первые 5 записей

In [136]:
food.head()

code                                                url  \
0  0000000003087  http://world-en.openfoodfacts.org/product/0000...   
1  0000000004530  http://world-en.openfoodfacts.org/product/0000...   
2  0000000004559  http://world-en.openfoodfacts.org/product/0000...   
3  0000000016087  http://world-en.openfoodfacts.org/product/0000...   
4  0000000016094  http://world-en.openfoodfacts.org/product/0000...   

                      creator   created_t      created_datetime  \
0  openfoodfacts-contributors  1474103866  2016-09-17T09:17:46Z   
1             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
2             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
3             usda-ndb-import  1489055731  2017-03-09T10:35:31Z   
4             usda-ndb-import  1489055653  2017-03-09T10:34:13Z   

  last_modified_t last_modified_datetime                    product_name  \
0      1474103893   2016-09-17T09:18:13Z              Farine de blé noir   
1      1489069957   2017-03-09T14:32:37Z  Banana Chips Sweetened (Whole)   
2      1489069957   2017-03-09T14:32:37Z                         Peanuts   
3      1489055731   2017-03-09T10:35:31Z          Organic Salted Nut Mix   
4      1489055653   2017-03-09T10:34:13Z                 Organic Polenta   

  generic_name quantity         ...         fruits-vegetables-nuts_100g  \
0          NaN      1kg         ...                                 NaN   
1          NaN      NaN         ...                                 NaN   
2          NaN      NaN         ...                                 NaN   
3          NaN      NaN         ...                                 NaN   
4          NaN      NaN         ...                                 NaN   

  fruits-vegetables-nuts-estimate_100g collagen-meat-protein-ratio_100g  \
0                                  NaN                              NaN   
1                                  NaN                              NaN   
2                                  NaN                              NaN   
3                                  NaN                              NaN   
4                                  NaN                              NaN   

  cocoa_100g chlorophyl_100g carbon-footprint_100g nutrition-score-fr_100g  \
0        NaN             NaN                   NaN                     NaN   
1        NaN             NaN                   NaN                    14.0   
2        NaN             NaN                   NaN                     0.0   
3        NaN             NaN                   NaN                    12.0   
4        NaN             NaN                   NaN                     NaN   

  nutrition-score-uk_100g glycemic-index_100g water-hardness_100g  
0                     NaN                 NaN                 NaN  
1                    14.0                 NaN                 NaN  
2                     0.0                 NaN                 NaN  
3                    12.0                 NaN                 NaN  
4                     NaN                 NaN                 NaN  

[5 rows x 163 columns]

Сколько наблюдений в наборе данных?


In [110]:
sh = food.shape
lines_count = sh[0]
lines_count

356027

Сколько столбцов в наборе данных?

In [111]:
rows_count = sh[1]
rows_count

163

Напечатайте все названия столбцов

In [114]:
colums_name = list(food.columns.values)
colums_name

['code',
 'url',
 'creator',
 'created_t',
 'created_datetime',
 'last_modified_t',
 'last_modified_datetime',
 'product_name',
 'generic_name',
 'quantity',
 'packaging',
 'packaging_tags',
 'brands',
 'brands_tags',
 'categories',
 'categories_tags',
 'categories_en',
 'origins',
 'origins_tags',
 'manufacturing_places',
 'manufacturing_places_tags',
 'labels',
 'labels_tags',
 'labels_en',
 'emb_codes',
 'emb_codes_tags',
 'first_packaging_code_geo',
 'cities',
 'cities_tags',
 'purchase_places',
 'stores',
 'countries',
 'countries_tags',
 'countries_en',
 'ingredients_text',
 'allergens',
 'allergens_en',
 'traces',
 'traces_tags',
 'traces_en',
 'serving_size',
 'no_nutriments',
 'additives_n',
 'additives',
 'additives_tags',
 'additives_en',
 'ingredients_from_palm_oil_n',
 'ingredients_from_palm_oil',
 'ingredients_from_palm_oil_tags',
 'ingredients_that_may_be_from_palm_oil_n',
 'ingredients_that_may_be_from_palm_oil',
 'ingredients_that_may_be_from_palm_oil_tags',
 'nutritio

Какое название у 105 столбца?

In [117]:
col_105 = colums_name[104]
col_105

'-glucose_100g'

Какой тип наблюдений в 105 столбце?

In [118]:
type(col_105)

str

Как проиндексирован набор данных?

In [123]:
food.index

RangeIndex(start=0, stop=356027, step=1)

Каково значение имени продукта в 19-м наблюдении?

In [127]:
product_name_19 = food['product_name'][18]
product_name_19

'Lotus Organic Brown Jasmine Rice'

## Pandas - фильтрация данных

Считать данные по  [адресу](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv). 
Присвоить переменной chipo

In [131]:
chipo = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv', sep='\t')
chipo.head()

order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   

                                  choice_description item_price  
0                                                NaN     $2.39   
1                                       [Clementine]     $3.39   
2                                            [Apple]     $3.39   
3                                                NaN     $2.39   
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98

Как много продуктов стоят более чем $10.00?

In [155]:
chipo['item_price_float'] = pd.Series(chipo['item_price'].replace('[\$,]', '', regex=True).astype(float), index = chipo.index)
chipo.head()
chipo[chipo['item_price_float'] > 10].shape[0]

1130

Какова цена каждого предмета? Напечатать столбцы item_name и item_price

In [162]:
chipo[['item_name','item_price']]

item_name item_price
0              Chips and Fresh Tomato Salsa     $2.39 
1                                      Izze     $3.39 
2                          Nantucket Nectar     $3.39 
3     Chips and Tomatillo-Green Chili Salsa     $2.39 
4                              Chicken Bowl    $16.98 
5                              Chicken Bowl    $10.98 
6                             Side of Chips     $1.69 
7                             Steak Burrito    $11.75 
8                          Steak Soft Tacos     $9.25 
9                             Steak Burrito     $9.25 
10                      Chips and Guacamole     $4.45 
11                     Chicken Crispy Tacos     $8.75 
12                       Chicken Soft Tacos     $8.75 
13                             Chicken Bowl    $11.25 
14                      Chips and Guacamole     $4.45 
15    Chips and Tomatillo-Green Chili Salsa     $2.39 
16                          Chicken Burrito     $8.49 
17                          Chicken Burrito     $8.49 
18                              Canned Soda     $2.18 
19                             Chicken Bowl     $8.75 
20                      Chips and Guacamole     $4.45 
21                         Barbacoa Burrito     $8.99 
22                         Nantucket Nectar     $3.39 
23                          Chicken Burrito    $10.98 
24                                     Izze     $3.39 
25             Chips and Fresh Tomato Salsa     $2.39 
26                             Chicken Bowl     $8.49 
27                         Carnitas Burrito     $8.99 
28                              Canned Soda     $1.09 
29                          Chicken Burrito     $8.49 
...                                     ...        ...
4592                       Barbacoa Burrito    $11.75 
4593                          Carnitas Bowl    $11.75 
4594                          Barbacoa Bowl    $11.75 
4595                           Chicken Bowl     $8.75 
4596                    Chips and Guacamole     $4.45 
4597                      Canned Soft Drink     $1.25 
4598                          Bottled Water     $1.50 
4599                           Chicken Bowl     $8.75 
4600                    Chips and Guacamole     $4.45 
4601                      Canned Soft Drink     $1.25 
4602                       Barbacoa Burrito     $9.25 
4603                       Barbacoa Burrito     $9.25 
4604                           Chicken Bowl     $8.75 
4605                    Chips and Guacamole     $4.45 
4606                      Canned Soft Drink     $1.25 
4607                          Steak Burrito    $11.75 
4608                         Veggie Burrito    $11.25 
4609                      Canned Soft Drink     $1.25 
4610                          Steak Burrito    $11.75 
4611                         Veggie Burrito    $11.25 
4612                          Carnitas Bowl     $9.25 
4613                                  Chips     $2.15 
4614                          Bottled Water     $1.50 
4615                     Chicken Soft Tacos     $8.75 
4616                    Chips and Guacamole     $4.45 
4617                          Steak Burrito    $11.75 
4618                          Steak Burrito    $11.75 
4619                     Chicken Salad Bowl    $11.25 
4620                     Chicken Salad Bowl     $8.75 
4621                     Chicken Salad Bowl     $8.75 

[4622 rows x 2 columns]

Отсортировать по имени предмета

In [164]:
chipo.sort_values(by=['item_name'])

order_id  quantity          item_name  \
3389      1360         2  6 Pack Soft Drink   
341        148         1  6 Pack Soft Drink   
1849       749         1  6 Pack Soft Drink   
1860       754         1  6 Pack Soft Drink   
2713      1076         1  6 Pack Soft Drink   
3422      1373         1  6 Pack Soft Drink   
553        230         1  6 Pack Soft Drink   
1916       774         1  6 Pack Soft Drink   
1922       776         1  6 Pack Soft Drink   
1937       784         1  6 Pack Soft Drink   
3836      1537         1  6 Pack Soft Drink   
298        129         1  6 Pack Soft Drink   
1976       798         1  6 Pack Soft Drink   
1167       481         1  6 Pack Soft Drink   
3875      1554         1  6 Pack Soft Drink   
1124       465         1  6 Pack Soft Drink   
3886      1558         1  6 Pack Soft Drink   
2108       849         1  6 Pack Soft Drink   
3010      1196         1  6 Pack Soft Drink   
4535      1803         1  6 Pack Soft Drink   
4169      1664         1  6 Pack Soft Drink   
4174      1666         1  6 Pack Soft Drink   
4527      1800         1  6 Pack Soft Drink   
4522      1798         1  6 Pack Soft Drink   
3806      1525         1  6 Pack Soft Drink   
2389       949         1  6 Pack Soft Drink   
3132      1248         1  6 Pack Soft Drink   
3141      1253         1  6 Pack Soft Drink   
639        264         1  6 Pack Soft Drink   
1026       422         1  6 Pack Soft Drink   
...        ...       ...                ...   
2996      1192         1       Veggie Salad   
3163      1263         1       Veggie Salad   
4084      1635         1       Veggie Salad   
1694       686         1       Veggie Salad   
2756      1094         1       Veggie Salad   
4201      1677         1  Veggie Salad Bowl   
1884       760         1  Veggie Salad Bowl   
455        195         1  Veggie Salad Bowl   
3223      1289         1  Veggie Salad Bowl   
2223       896         1  Veggie Salad Bowl   
2269       913         1  Veggie Salad Bowl   
4541      1805         1  Veggie Salad Bowl   
3293      1321         1  Veggie Salad Bowl   
186         83         1  Veggie Salad Bowl   
960        394         1  Veggie Salad Bowl   
1316       536         1  Veggie Salad Bowl   
2156       869         1  Veggie Salad Bowl   
4261      1700         1  Veggie Salad Bowl   
295        128         1  Veggie Salad Bowl   
4573      1818         1  Veggie Salad Bowl   
2683      1066         1  Veggie Salad Bowl   
496        207         1  Veggie Salad Bowl   
4109      1646         1  Veggie Salad Bowl   
738        304         1  Veggie Soft Tacos   
3889      1559         2  Veggie Soft Tacos   
2384       948         1  Veggie Soft Tacos   
781        322         1  Veggie Soft Tacos   
2851      1132         1  Veggie Soft Tacos   
1699       688         1  Veggie Soft Tacos   
1395       567         1  Veggie Soft Tacos   

                                     choice_description item_price  \
3389                                        [Diet Coke]    $12.98    
341                                         [Diet Coke]     $6.49    
1849                                             [Coke]     $6.49    
1860                                        [Diet Coke]     $6.49    
2713                                             [Coke]     $6.49    
3422                                             [Coke]     $6.49    
553                                         [Diet Coke]     $6.49    
1916                                        [Diet Coke]     $6.49    
1922                                             [Coke]     $6.49    
1937                                        [Diet Coke]     $6.49    
3836                                             [Coke]     $6.49    
298                                            [Sprite]     $6.49    
1976                                        [Diet Coke]     $6.49    
1167                                             [Coke]     $6.49    
3875                                     

Сколько было заказано самого дорогого предмета?

In [ ]:
chipo.loc[chipo['item_price_float'].idxmax()]['quantity']

15

Сколько раз был заказан предмет "Veggie Salad Bowl"?

In [182]:
chipo[chipo['item_name'] == 'Veggie Salad Bowl']['quantity'].sum()

18

Сколько раз люди заказали более чем 1 предмет "Canned Soda"?

In [180]:
chipo[chipo['quantity'] > 1].shape[0]

267